// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnMAeJcmg6rij7jr5HCbZ-ZPwhn0F2Gs',
    appId: '1:653809417802:web:4d841676a4ffb2ad3970b3',
    messagingSenderId: '653809417802',
    projectId: 'sohoms-insta-clone',
    authDomain: 'sohoms-insta-clone.firebaseapp.com',
    storageBucket: 'sohoms-insta-clone.appspot.com',
    measurementId: 'G-JCY71JBHHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVS4gUMjvJ_uSEb_ZiIPMGpAy1u6g4PE',
    appId: '1:653809417802:android:7f1d0c4656d6e9823970b3',
    messagingSenderId: '653809417802',
    projectId: 'sohoms-insta-clone',
    storageBucket: 'sohoms-insta-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW7fqNS5q0GYMFN9aC_fVwZAPCixy3n7o',
    appId: '1:653809417802:ios:b01c691dd43a557a3970b3',
    messagingSenderId: '653809417802',
    projectId: 'sohoms-insta-clone',
    storageBucket: 'sohoms-insta-clone.appspot.com',
    iosClientId: '653809417802-f5pba943f5fnn96nvgi61alh334mhb34.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW7fqNS5q0GYMFN9aC_fVwZAPCixy3n7o',
    appId: '1:653809417802:ios:b01c691dd43a557a3970b3',
    messagingSenderId: '653809417802',
    projectId: 'sohoms-insta-clone',
    storageBucket: 'sohoms-insta-clone.appspot.com',
    iosClientId: '653809417802-f5pba943f5fnn96nvgi61alh334mhb34.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
